


motd: |
    Welcome to the server

username: root
password: password
port: 2000

simple_commands:
    whoami:
        output: root
    sudo:
        output: You are already root why use sudo, are you dumb?
    ls:
        output: bin boot dev etc home lib media mnt opt root sbin




pem_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIICXQIBAAKBgQC+m7N84jioc4atxTZI7vS/4lFlN9p8t9HDCOTXTG06/eluwj4a
    yDmQemZmSoqs6E7um+SWfIvCB+CM1Ghs61GRhtvmp5QDcDMn2bgCBs/tie35WDgN
    fcpqpBrZYfDZ+0WU35n0ugjfRB3qeo2YJT8aofOEj703jfKp0l5Xth1OWQIDAQAB
    AoGAJWD7Td4/Jimhm6o0/xB9RrPnKmZNnm+d3xV7aw09znfEs0e8Thw9zatzMVQk
    5cuYzwobRbee4KoSywtMfy+WixCl5ozk0Dh/F9R8O0eZwXFAGRqC0T7W6/ntJF/9
    NKZHTQHoy2SjuL6T2LWUNhJSXcqkr4nfJncCFfaxgNI2JAECQQDUM7S65BceqP7F
    /QDtJIX7zLlfTilFnI55A1RCyfV6snjWSagXHJW5Emwe3lbYsseAo3FDKPMQMxcy
    cLqt6eL5AkEA5fMG7GGUQAZKJrE1c3GytbLFiZt+rccuTDcGpyC+qpCnXbwTUhG1
    I9owKtMdyufzQmim4267uUFtAIGpYzY+YQJBANNvQaEGK9Ms5842rXmcbrPZ5MqF
    grINsBf7rTVvLd03fxdlBMsifDyPkpOfTkFUwVv3fp9Aag+2GGL118v5w2ECQQCp
    A4nxMH+w126lJdcttUIvfujmjd38iMwkxMUlDlJWN+BsaxKgXdeQNIz2zRm2y+nm
    w9j2jat5LPebSbJg87vBAkAvQa4Fsam4MiXC6FgnXGm/eRYT3OIImPJp2575uiXI
    jn2Xx9uQnp6HrtdpTE4qrKKUrw/yKPVILzL4eM6X7bFk
    -----END RSA PRIVATE KEY-----

pub_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQC+m7N84jioc4atxTZI7vS/4lFlN9p8t9HDCOTXTG06/eluwj4ayDmQemZmSoqs6E7um+SWfIvCB+CM1Ghs61GRhtvmp5QDcDMn2bgCBs/tie35WDgNfcpqpBrZYfDZ+0WU35n0ugjfRB3qeo2YJT8aofOEj703jfKp0l5Xth1OWQ==

    
