version: '3'
services:
  honey:
    image: banjocat/walter_honey:latest
    build: .
    volumes:
      - ./honey/.:/app
    ports:
      - "2000:2000"
  nginx:
    image: nginx:1.10-alpine
    volumes:
      - "./nginx.conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx.conf/demo_server.crt:/etc/nginx/site.crt"
      - "./nginx.conf/demo_server.key:/etc/nginx/site.key"
      - "./nginx.conf/demo_client.crt:/etc/nginx/client.crt"
    ports:
      - "8888:80"
      - "9999:443"
    depends_on:
      - kibana
  elastic:
    image: elastic/elasticsearch:6.2.3
    environment:
      discovery.type: single-node
  kibana:
    image: elastic/kibana:6.2.3
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elastic:9200
    ports:
      - "5601:5601"
    depends_on:
      - elastic
  freegeoip:
    image: fiorix/freegeoip
  elastalert:
    build: ./elastalert
    environment:
      ES_HOST: elastic
      ES_PORT: 9200
    volumes:
      - ./elastalert:/etc/elastalert


