

username: root
password: password
port: 2000

motd: |
    Welcome to the server


simple_commands:
    whoami: root
    sudo: You are already root why use sudo, are you dumb?
    ls: bin boot dev etc home lib media mnt opt root sbin
    ps: |
        PID TTY          TIME CMD
        3753 pts/18   00:00:00 bash
        3795 pts/18   00:00:00 ps
    who: |
        root tty7         2016-10-03 00:52 (:0)
        root pts/18       2016-10-06 22:01 (:0)
        root pts/0        2016-10-06 21:56 (:0)
        root pts/19       2016-10-05 23:36 (:0)
    reboot: No. I will not
    apt-get: Debian sucks.
    apt: Debian sucks.
    yum: Red hat sucks.
    pacman: Archlinux sucks.
    zypper: OpenSUSE sucks.
    emerge: Gentoo sucks.
    brew: Macs really suck.




pem_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIICXQIBAAKBgQC+m7N84jioc4atxTZI7vS/4lFlN9p8t9HDCOTXTG06/eluwj4a
    yDmQemZmSoqs6E7um+SWfIvCB+CM1Ghs61GRhtvmp5QDcDMn2bgCBs/tie35WDgN
    fcpqpBrZYfDZ+0WU35n0ugjfRB3qeo2YJT8aofOEj703jfKp0l5Xth1OWQIDAQAB
    AoGAJWD7Td4/Jimhm6o0/xB9RrPnKmZNnm+d3xV7aw09znfEs0e8Thw9zatzMVQk
    5cuYzwobRbee4KoSywtMfy+WixCl5ozk0Dh/F9R8O0eZwXFAGRqC0T7W6/ntJF/9
    NKZHTQHoy2SjuL6T2LWUNhJSXcqkr4nfJncCFfaxgNI2JAECQQDUM7S65BceqP7F
    /QDtJIX7zLlfTilFnI55A1RCyfV6snjWSagXHJW5Emwe3lbYsseAo3FDKPMQMxcy
    cLqt6eL5AkEA5fMG7GGUQAZKJrE1c3GytbLFiZt+rccuTDcGpyC+qpCnXbwTUhG1
    I9owKtMdyufzQmim4267uUFtAIGpYzY+YQJBANNvQaEGK9Ms5842rXmcbrPZ5MqF
    grINsBf7rTVvLd03fxdlBMsifDyPkpOfTkFUwVv3fp9Aag+2GGL118v5w2ECQQCp
    A4nxMH+w126lJdcttUIvfujmjd38iMwkxMUlDlJWN+BsaxKgXdeQNIz2zRm2y+nm
    w9j2jat5LPebSbJg87vBAkAvQa4Fsam4MiXC6FgnXGm/eRYT3OIImPJp2575uiXI
    jn2Xx9uQnp6HrtdpTE4qrKKUrw/yKPVILzL4eM6X7bFk
    -----END RSA PRIVATE KEY-----

pub_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQC+m7N84jioc4atxTZI7vS/4lFlN9p8t9HDCOTXTG06/eluwj4ayDmQemZmSoqs6E7um+SWfIvCB+CM1Ghs61GRhtvmp5QDcDMn2bgCBs/tie35WDgNfcpqpBrZYfDZ+0WU35n0ugjfRB3qeo2YJT8aofOEj703jfKp0l5Xth1OWQ==

    
